server:
  port: 8080
  trustedPort: 8083
  trustedPathPrefix: /internal/

spring:
  application:
    name: spring-boot-task-schedule
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
#    password: root
    password: ENC(0ancQnPjH43FO474e7fmqA==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: MyHikariCP
      maximum-pool-size: 15

  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clustereScheduler #调度器的实例名
            instanceInd: AUTO #调度器编号自动生成
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #作业存储类型
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: qrtz_ #数据库表名前缀
            isClusterex: true # 开启分布式部署
            clusterCheckinInterval: 10000 # 分布式节点有效性检查时间间隔，单位：秒
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool #自带的线程池实现类
            threadCount: 10 #开启10个线程
            threadPriority: 5 #工作线程的优先级
            threadsInheritContextClassLocaderOfInitializingThread: true
    # 数据存储方式
    job-store-type: jdbc










  # 邮箱主机地址
  mail:
    host: smtp.qq.com
  # 端口
    port: 25
    username: 1914866205@qq.com
    password: dhykrfydapzxijhb
    default-encoding: UTF-8

  # 配置文件项加解密密码，此处作为测试完，实际情况应该注释，而放在代码中（放在代码中使加密密钥和密文分开）
jasypt:
  encryptor:
    password: salt
